# Generated by Django 6.0 on 2026-01-05 05:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], default='beginner', max_length=20)),
                ('favorite_activities', models.JSONField(default=list, help_text='List of favorite activity types')),
                ('fitness_goals', models.JSONField(default=list, help_text='List of fitness goals')),
                ('looking_for', models.JSONField(default=list, help_text='What user is looking for: workout_partner, running_buddy, gym_buddy, etc.')),
                ('preferred_age_min', models.IntegerField(default=18)),
                ('preferred_age_max', models.IntegerField(default=100)),
                ('preferred_distance_miles', models.IntegerField(default=25, help_text='Max distance in miles')),
                ('preferred_gender', models.JSONField(default=list, help_text='List of preferred genders to match with')),
                ('prompt_question', models.CharField(default='Ask me about my post-run snack routine 🥑', help_text='Fun prompt to start conversations', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Profile visible in matching')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('unmatched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('unmatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatches_initiated', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['-matched_at'],
                'indexes': [models.Index(fields=['user1', 'is_active'], name='matches_user1_i_011e58_idx'), models.Index(fields=['user2', 'is_active'], name='matches_user2_i_23570b_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('super_like', 'Super Like')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swipe',
                'verbose_name_plural': 'Swipes',
                'db_table': 'swipes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user', 'action'], name='swipes_from_us_9bac12_idx'), models.Index(fields=['to_user', 'action'], name='swipes_to_user_115469_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
