# Generated by Django 6.0 on 2026-09-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Height in centimetres', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Body weight in kilograms', null=True),
        ),
    ]
