# Generated by Django 6.0 on 2026-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Run', 'Run'), ('Cycle', 'Cycle'), ('Walk', 'Walk'), ('Swim', 'Swim'), ('Yoga', 'Yoga'), ('Strength', 'Strength')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('distance', models.FloatField(blank=True, help_text='Distance in meters', null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('average_speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Pace in min/km', null=True)),
                ('elevation_gain', models.FloatField(blank=True, help_text='Elevation in meters', null=True)),
                ('heart_rate_avg', models.IntegerField(blank=True, null=True)),
                ('heart_rate_max', models.IntegerField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('start_address', models.CharField(blank=True, max_length=500)),
                ('route', models.JSONField(blank=True, help_text='Array of route points with lat/lng/altitude/speed/timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_steps', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(default=0.0, help_text='Distance in meters')),
                ('total_calories', models.IntegerField(default=0)),
                ('total_active_minutes', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('step_goal_progress', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('calorie_goal_progress', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('workout_goal_progress', models.FloatField(default=0.0, help_text='Percentage 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Summary',
                'verbose_name_plural': 'Daily Summaries',
                'db_table': 'daily_summaries',
                'ordering': ['-date'],
            },
        ),
    ]
