# Generated by Django 6.0 on 2026-01-05 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Run', 'Run'), ('Cycle', 'Cycle'), ('Walk', 'Walk'), ('Swim', 'Swim'), ('Yoga', 'Yoga'), ('Strength', 'Strength')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_duration', models.IntegerField(default=0, help_text='Total paused time in seconds')),
                ('current_distance', models.FloatField(default=0.0, help_text='Distance in meters')),
                ('current_duration', models.IntegerField(default=0, help_text='Active duration in seconds')),
                ('current_calories', models.IntegerField(default=0)),
                ('current_pace', models.FloatField(blank=True, help_text='Current pace in min/km', null=True)),
                ('current_speed', models.FloatField(blank=True, help_text='Current speed in km/h', null=True)),
                ('route_points', models.JSONField(default=list, help_text='Array of GPS points: [{lat, lng, altitude, speed, timestamp, accuracy}]')),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_session', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Activity',
                'verbose_name_plural': 'Live Activities',
                'db_table': 'live_activities',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='live_activi_user_id_ef0b1c_idx'), models.Index(fields=['-start_time'], name='live_activi_start_t_0c71d8_idx')],
            },
        ),
    ]
