# Generated by Django 6.0 on 2026-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_liveactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone'), ('followers', 'Followers'), ('private', 'Only me')], default='public', help_text='Who can see this activity in the feed', max_length=20),
        ),
    ]
